#- name: PAKAGES | Add repositories
#  apt_repository: repo='ppa:stefansundin/truecrypt'

- name: PAKAGES | Install the packages in ubuntu
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
      - p7zip-full
      - zip
      - ntp
      - ntpdate
