- name: USER | add user
  action: user name={{ user }} password={{ password }} update_password=always 
                   shell=/bin/bash home=/home/{{ user }} groups=sudo append=yes

- name: USER | add user1
  action: user name={{ user1 }} password={{ password }} update_password=always
                   shell=/bin/bash home=/home/{{ user1 }} groups=sudo append=yes

- name: USER | add user2
  action: user name={{ user2 }} password={{ password }} update_password=always
                   shell=/bin/bash home=/home/{{ user2 }} groups=sudo append=yes

- name: USER | add user3
  action: user name={{ user3 }} password={{ password }} update_password=always
                   shell=/bin/bash home=/home/{{ user3 }} #groups=sudo append=yes
                   
- name: USER | add user4
  action: user name={{ user4 }} password={{ password }} update_password=always
                  shell=/bin/bash home=/home/{{ user4 }}  groups=sudo append=yes
- name: USER | add user5
  action: user name={{ user5 }} password={{ password }} update_password=always
                   shell=/bin/bash home=/home/{{ user5 }} #groups=sudo append=yes
 
 - name: USER | add user6
  action: user name={{ user6 }} password={{ password }} update_password=always
                  shell=/bin/bash home=/home/{{ user6 }} #groups=sudo append=yes

- name: USER | add user7
  action: user name={{ user7 }} password={{ password }} update_password=always
                  shell=/bin/bash home=/home/{{ user7 }} #groups=sudo append=yes

- name: USER | add user8
  action: user name={{ user8 }} password={{ password }} update_password=always
                  shell=/bin/bash home=/home/{{ user8 }}  groups=sudo append=yes                                   
                                   
- name: USER | add user9
  action: user name={{ user9 }} password={{ password }} update_password=always
                   shell=/bin/bash home=/home/{{ user9 }} groups=sudo append=yes

- name: USER | add user10
  action: user name={{ user10 }} password={{ password }} update_password=always
                 shell=/bin/bash home=/home/{{ user10 }}  #groups=sudo append=yes

#- name: USER | add user11
#  action: user name={{ user11 }} password={{ password }} update_password=always
#                  shell=/bin/bash home=/home/{{ user11 }} #groups=sudo append=yes




#Force users to change password at first login

- name: Expiring password for user "{{ user }}"
  shell: chage -d 0 "{{ user }}"

- name: Expiring password for user "{{ user1 }}"
  shell: chage -d 0 "{{ user1 }}"
- name: Expiring password for user "{{ user2 }}"
  shell: chage -d 0 "{{ user2 }}"
- name: Expiring password for user "{{ user3 }}"
  shell: chage -d 0 "{{ user3 }}" 
- name: Expiring password for user "{{ user4 }}"
  shell: chage -d 0 "{{ user4 }}"
- name: Expiring password for user "{{ user5 }}"
  shell: chage -d 0 "{{ user5 }}"
- name: Expiring password for user "{{ user6 }}"
  shell: chage -d 0 "{{ user6 }}" 
- name: Expiring password for user "{{ user7 }}"
  shell: chage -d 0 "{{ user7 }}"
- name: Expiring password for user "{{ user8 }}"
  shell: chage -d 0 "{{ user8 }}"     
- name: Expiring password for user "{{ user9 }}"
  shell: chage -d 0 "{{ user9 }}"
#- name: Expiring password for user "{{ user10 }}"
#  shell: chage -d 0 "{{ user10 }}"
  
