
# Configure and install mysql

- name: Set MySQL root password
  debconf: name=mysql-server question=mysql-server/root_password value={{ openmrs_db_root_password }} vtype=password
  no_log: true

- name: Confirm MySQL root password
  debconf: name=mysql-server question=mysql-server/root_password_again value={{ openmrs_db_root_password }} vtype=password
  no_log: true

- name: Install MySQL
  apt: name={{ openmrs_db_mysql_version }} state=latest

- name: Configure MySQL
  template:
    src: mysql.cnf.j2
    dest: "/etc/mysql/conf.d/mysql.cnf"
    owner: "root"
    group: "root"
    mode: 0644

- name: Restart MySQL
  service: name=mysql state=restarted
