  - name: Check if service exist
    stat: path=/etc/init.d/{{service_name}}
    register: service_status
  
  - name: Stop service if exist
    service: name={{service_name}} state=stopped
    when: service_status.stat.exists
    register: service_stopped

