  - name: Check and copy certs folder exist
    copy: src=files/certs dest={{ ssl_certs_folder }} owner=root
    ignore_errors: true
  
  - name: Check and copy Private folder exist
    copy: src=files/private dest={{ ssl_certs_folder }} owner=root
    ignore_errors: true

  - name: Add lines in ssl.conf 
    lineinfile: dest={{ ssl_conf_path }}/{{ ssl_conf }} regexp={{ item.key }} line={{ item.value }}
    with_items:
      - { key: "{{ SSLCertificateFile }}", value: "SSLCertificateFile {{ CertificateFile }}" }
      - { key: "{{ SSLCertificateKeyFile }}", value: "SSLCertificateKeyFile {{ CertificateKeyFile }}" }
      - { key: "{{ SSLCertificateChainFile }}", value: "SSLCertificateChainFile {{ CertificateChainFile }}" }

  - name: Start service
    service: name={{service_name}} state=started enabled=yes
