Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.33.21"
  config.vm.provider "virtualbox" do |vb|
      vb.name = "rwandaemr2004"
      vb.customize ["modifyvm", :id, "--memory", "3072", "--cpus", "2"]
  end
  config.vm.hostname = "rwandaemr2004"
end
