
openmrs_user: "openmrs"
openmrs_group: "{{ openmrs_user }}"
openmrs_home: "/home/openmrs"
openmrs_data_dir: "{{ openmrs_home }}/data"
openmrs_tomcat_home: "{{ openmrs_home }}/tomcat"
openmrs_distro_dir: "{{ openmrs_home }}/distribution"

openmrs_java_version: "11"
openmrs_tomcat_version: "9.0.40"

openmrs_java_package: "openjdk-11-jdk"
openmrs_java_home: "/usr/lib/jvm/java-{{ openmrs_java_version }}-openjdk-amd64"

openmrs_tomcat_package: "apache-tomcat-{{ openmrs-tomcat-version }}"
openmrs_tomcat_url: "https://mirrors.sonic.net/apache/tomcat/tomcat-9/v{{ openmrs_tomcat_version }}/bin/{{ openmrs_tomcat_package }}.zip"

openmrs_tomcat_catalina_opts: "-Xms1024M -Xmx2048M -server -XX:+UseParallelGC -XX:NewSize=128m -DOPENMRS_APPLICATION_DATA_DIRECTORY={{ openmrs_data_dir }}/"
openmrs_tomcat_java_opts: "-Dfile.encoding=UTF-8 -Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true -Djava.awt.headlesslib=true"

openmrs_distro_group_id: "org.openmrs.distro"
openmrs_distro_artifact_id: "rwandaemr-imb"
openmrs_distro_version: "2.0.0-SNAPSHOT"
openmrs_distro_type: "zip"
openmrs_distro_classifier: "distribution"

openmrs_distro_maven_artifact: "{{ openmrs_distro_group_id }}:{{ openmrs_distro_artifact_id }}:{{ openmrs_distro_version }}:{{ openmrs_distro_type }}:{{ openmrs_distro_classifier }}"
openmrs_distro_artifact_dir: "{{ openmrs_distro_dir }}/{{ openmrs_distro_artifact_id }}-{{ openmrs_distro_version }}"
openmrs_distro_artifact_file: "{{ openmrs_distro_artifact_id }}-{{ openmrs_distro_version }}-{{ openmrs_distro_classifier }}.{{ openmrs_distro_type }}"

openmrs_db_root_password: "root"
openmrs_db_openmrs_user: "openmrs"
openmrs_db_openmrs_password: "openmrs"
openmrs_db_connection_args: "autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false"
