
openmrs_user: "openmrs"
openmrs_group: "{{ openmrs_user }}"
openmrs_home: "/home/openmrs"
openmrs_data_dir: "{{ openmrs_home }}/data"
openmrs_tomcat_home: "{{ openmrs_home }}/tomcat"
openmrs_distro_dir: "{{ openmrs_home }}/distribution"

#openmrs_java_package: "openjdk-11-jdk"
#openmrs_java_home: "/usr/lib/jvm/java-11-openjdk-amd64"

#openmrs_tomcat_package: "apache-tomcat-9.0.40"
#openmrs_tomcat_url: "https://mirrors.sonic.net/apache/tomcat/tomcat-7/v7.0.108/bin/apache-tomcat-7.0.108.zip"

openmrs_java_package: "openjdk-8-jdk"
openmrs_java_home: "/usr/lib/jvm/java-8-openjdk-amd64"

openmrs_tomcat_package: "apache-tomcat-7.0.108"
openmrs_tomcat_url: "https://mirrors.sonic.net/apache/tomcat/tomcat-7/v7.0.108/bin/apache-tomcat-7.0.108.zip"

openmrs_tomcat_catalina_opts: "-Xms1024M -Xmx2048M -server -XX:+UseParallelGC -XX:NewSize=128m -DOPENMRS_APPLICATION_DATA_DIRECTORY={{ openmrs_data_dir }}/"
openmrs_tomcat_java_opts: "-Dfile.encoding=UTF-8 -Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true -Djava.awt.headlesslib=true"

# Enables debugging to be enabled
openmrs_tomcat_debug_opts: ""
#openmrs_tomcat_debug_opts: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000"

openmrs_distro_site: ""
openmrs_distro_group_id: "org.openmrs.distro"
openmrs_distro_artifact_id: "rwandaemr-imb-{{ openmrs_distro_site }}"
openmrs_distro_version: "2.0.0-SNAPSHOT"
openmrs_distro_type: "zip"
openmrs_distro_classifier: "distribution"

openmrs_distro_maven_artifact: "{{ openmrs_distro_group_id }}:{{ openmrs_distro_artifact_id }}:{{ openmrs_distro_version }}:{{ openmrs_distro_type }}:{{ openmrs_distro_classifier }}"
openmrs_distro_artifact_dir: "{{ openmrs_distro_dir }}/{{ openmrs_distro_artifact_id }}-{{ openmrs_distro_version }}"
openmrs_distro_artifact_file: "{{ openmrs_distro_artifact_id }}-{{ openmrs_distro_version }}-{{ openmrs_distro_classifier }}.{{ openmrs_distro_type }}"

openmrs_db_root_password: "root"
openmrs_db_openmrs_user: "openmrs"
openmrs_db_openmrs_password: "openmrs"
openmrs_db_connection_args: "autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false"
